# Generated by Django 5.2.6 on 2025-09-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('Id_Autor', models.AutoField(db_column='T001IdAutor', editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='T001Nombre', max_length=100)),
                ('Apellido', models.CharField(db_column='T001Apellido', max_length=100)),
                ('Biografia', models.CharField(db_column='T001Biografia', max_length=500)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'T001Autor',
            },
        ),
    ]
