# Generated by Django 5.2.6 on 2025-09-05 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('Id_Editorial', models.AutoField(db_column='T002IdEditorial', editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='T002Nombre', max_length=100)),
                ('Direccion', models.CharField(db_column='T002Direccion', max_length=200)),
                ('Telefono', models.CharField(db_column='T002Telefono', max_length=15)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'db_table': 'T002Editorial',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('Id_Miembro', models.AutoField(db_column='T004IdMiembro', editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='T004Nombre', max_length=100)),
                ('Apellido', models.CharField(db_column='T004Apellido', max_length=100)),
                ('Email', models.CharField(db_column='T004Email', max_length=10)),
                ('Fecha_Mem', models.DateField(db_column='T004Fecha')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'T004Miembro',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('Id_Libro', models.AutoField(db_column='T003IdLibro', editable=False, primary_key=True, serialize=False)),
                ('Titulo', models.CharField(db_column='T003Titulo', max_length=100)),
                ('Resumen', models.CharField(db_column='T003Resumen', max_length=500)),
                ('ISBN', models.CharField(db_column='T003ISBN', max_length=13, unique=True)),
                ('Año_Pub', models.DateField(db_column='T003Año')),
                ('Id_Autor', models.ForeignKey(db_column='T003IdAutor', on_delete=django.db.models.deletion.CASCADE, to='api_app.autor')),
                ('Id_Editorial', models.ForeignKey(db_column='T003IdEditorial', on_delete=django.db.models.deletion.CASCADE, to='api_app.editorial')),
            ],
            options={
                'verbose_name': 'Titulo',
                'verbose_name_plural': 'Titulos',
                'db_table': 'T003Titulo',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('Id_Prestamo', models.AutoField(db_column='T005IdPrestamo', editable=False, primary_key=True, serialize=False)),
                ('Fecha_Prestamo', models.DateField(db_column='T005FechaPrestamo')),
                ('Fecha_Devolucion', models.DateField(db_column='T005FechaDevolucion')),
                ('Id_Libro', models.ForeignKey(db_column='T005IdLibro', on_delete=django.db.models.deletion.CASCADE, to='api_app.libro')),
                ('Id_Miembro', models.ForeignKey(db_column='T005IdMiembro', on_delete=django.db.models.deletion.CASCADE, to='api_app.miembro')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
                'db_table': 'T005Prestamo',
            },
        ),
    ]
