# Generated by Django 5.2.6 on 2025-09-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_editorial_miembro_libro_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='Email',
            field=models.CharField(db_column='T004Email', unique=True),
        ),
    ]
